"""
Sample queries for testing the accuracy of the semantic router.
Each expert has a list of sample queries that should be routed to them.
"""

samples = {
    "reinforcement_learning": [
        "What are the key components of Markov Decision Processes?",
        "Can you explain Q-learning algorithms?",
        "What's the difference between on-policy and off-policy DRL?",
        "How does Monte Carlo Tree Search work?",
        "What are the fundamental principles of multi-armed bandits?",
        "Explain the role of exploration vs exploitation in RL",
        "Tell me about AlphaGo Zero's reinforcement learning approach",
        "What is dynamic programming in reinforcement learning?",
        "How does tabular reinforcement learning differ from deep RL?",
        "What are actor-critic algorithms like DDPG and TD3?",
        "Can you explain offline reinforcement learning?",
        "What techniques are used for imitation learning?",
        "How do Deep Q-Networks work for Atari games?",
        "What is the Sutton and Barto approach to reinforcement learning?",
        "What are the main algorithms in off-policy reinforcement learning?",
        "What are value functions in reinforcement learning?",
        "How do policy gradient methods work?",
        "What are the pros and cons of offline DRL?",
        "Can you explain Monte Carlo methods in reinforcement learning?",
        "What's the significance of the Bellman equation in RL?",
        "How does reinforcement learning handle partial observability?",
        "What are the state-of-the-art techniques in deep reinforcement learning?",
        "How is MCTS used in reinforcement learning algorithms?",
        "What are the applications of imitation learning in robotics?",
        "How do you implement a basic Q-learning algorithm?",
    ],
    # "algorithms": [
    #     "What is the time complexity of mergesort?",
    #     "How does Dijkstra's algorithm find shortest paths?",
    #     "Explain the greedy approach for interval scheduling",
    #     "What's the difference between BFS and DFS traversal?",
    #     "How do dynamic programming algorithms work?",
    #     "Can you explain the Ford-Fulkerson algorithm?",
    #     "What are the applications of minimum spanning trees?",
    #     "How does Kruskal's algorithm differ from Prim's algorithm?",
    #     "What is asymptotic analysis of algorithms?",
    #     "How to implement topological sorting for directed acyclic graphs?",
    #     "What are Huffman codes used for in data compression?",
    #     "Explain how the closest pair of points algorithm works",
    #     "How does the FFT algorithm improve integer multiplication?",
    #     "What is the Bellman-Ford algorithm used for?",
    #     "Can you explain how sequence alignment algorithms work?",
    #     "What are polynomial time reductions in computational complexity?",
    #     "How do approximation algorithms handle NP-complete problems?",
    #     "What makes an algorithm NP-complete?",
    #     "How do randomized algorithms improve efficiency?",
    #     "What is the knapsack problem and its dynamic programming solution?",
    #     "How does graph connectivity relate to algorithm design?",
    #     "What's the difference between on-policy and off-policy algorithms?",
    #     "Explain the concept of network flows and minimum cuts",
    #     "How does the Subset Sum algorithm work?",
    #     "What are the limitations of divide and conquer algorithms?"
    # ],
    "applied_machine_learning": [
        "How do support vector machines work for classification?",
        "What is the difference between supervised and unsupervised learning?",
        "How can I implement linear regression in Python?",
        "What are the best practices for data preprocessing in machine learning?",
        "How do neural networks handle image classification tasks?",
        "What is the mathematics behind decision trees?",
        "Can you explain the K-means clustering algorithm?",
        "How do convolutional neural networks recognize objects in images?",
        "What is dimensionality reduction and when should I use it?",
        "How can I implement a basic neural network using TensorFlow?",
        "What are the advantages of ensemble learning methods?",
        "How does random forest compare to a single decision tree?",
        "What is hierarchical clustering and how is it implemented?",
        "How do generative adversarial networks create synthetic data?",
        "What techniques can be used for hyperparameter tuning in machine learning?",
        "How does deep transfer learning improve model performance?",
        "What is YOLO and how does it detect objects in images?",
        "How can I use CNNs for image classification projects?",
        "What is the difference between L1 and L2 regularization?",
        "How do I implement K-nearest neighbors algorithm from scratch?",
        "What are the ethical considerations in machine learning applications?",
        "How can I evaluate the performance of a classification model?",
        "What is deep meta learning and its applications?",
        "How does unsupervised generative adversarial learning work?",
        "What Python libraries are essential for implementing machine learning algorithms?"
    ],
    "database_management": [
        "What is the difference between relational and document-oriented databases?",
        "How do I create a basic SQL query to retrieve data?",
        "What are the advantages of using MongoDB over traditional databases?",
        "Can you explain the concept of database normalization?",
        "How do I set up a Python environment for database work?",
        "What format should I use to store structured data - JSON or XML?",
        "How can I connect a database to a web application?",
        "What are the best practices for database design?",
        "How do spreadsheets like Excel function as databases?",
        "What is SQLite and when should I use it?",
        "How can I visualize data from my database effectively?",
        "What are the differences between CSV, JSON, and XML formats?",
        "How do I use Pandas for data analysis with Python?",
        "What is version control and why is it important for database projects?",
        "How do I set up a Jupyter Notebook for database work?",
        "What considerations should I make when choosing between different database systems?",
        "How do I implement data validation in my database?",
        "Can you explain how APIs connect to databases?",
        "What are the fundamentals of SQL programming?",
        "How is blockchain technology related to databases?",
        "What tools should I install for effective database development?",
        "How do I organize a database project using Git?",
        "What are the common problems databases are designed to solve?",
        "How do I handle unstructured data in database systems?",
        "What skills should I develop to work effectively with databases?"
    ],
    "computer_networks":[
        "How does TCP congestion control work?",
        "What is the difference between IPv4 and IPv6 addressing?",
        "How do routing algorithms determine the best path in networks?",
        "What is the purpose of DNS in computer networks?",
        "How does HTTP facilitate web communication?",
        "What are the key components of network security?",
        "How does reliable data transfer work in network protocols?",
        "What is the function of NAT in IP networking?",
        "How do peer-to-peer applications like BitTorrent work?",
        "What is the difference between UDP and TCP protocols?",
        "How does packet switching differ from circuit switching?",
        "What are the layers of the TCP/IP protocol stack?",
        "How does BGP enable routing between autonomous systems?",
        "What is the purpose of DHCP in network configuration?",
        "How do wireless networks handle multiple access control?",
        "What techniques are used for error detection and correction?",
        "How does Ethernet function at the link layer?",
        "What are the principles of network performance measurement?",
        "How do email protocols like SMTP and POP3 work?",
        "What is the role of the physical media in network transmission?",
        "How do distance vector routing protocols operate?",
        "What is ARP and why is it important for networking?",
        "How does FTP differ from HTTP for file transfers?",
        "What are the challenges in implementing large-scale networks?",
        "How does multiplexing work in network communications?"
    ],
    "computer_systems_organization":[
        "How do you write efficient memory allocation in C programming?",
        "What is the difference between stack and heap memory?",
        "How does the x86 processor handle integer representation?",
        "What are the fundamentals of buffer overflow attacks?",
        "How do I optimize C code for better performance?",
        "What happens during the linking process in computer systems?",
        "How does virtual memory work in modern operating systems?",
        "What is the process of reverse engineering assembly code?",
        "How are floating point numbers represented in binary?",
        "What are the key differences between assembly and machine code?",
        "How does cache memory improve system performance?",
        "What techniques are used for boolean algebra operations in low-level programming?",
        "How do procedure calls work at the assembly level?",
        "What is exceptional control flow in operating systems?",
        "How does bit manipulation work in C programming?",
        "What are the principles of memory hierarchy in computer architecture?",
        "How do arrays and structures get represented in memory?",
        "What optimization techniques can improve program execution speed?",
        "How does the Intel x86 processor handle control flow and loops?",
        "What is the relationship between C pointers and memory addresses?",
        "How do data types get stored and represented at the hardware level?",
        "What are the security implications of buffer overflow vulnerabilities?",
        "How does memory allocation work in C programming?",
        "What is the process of translating C code to assembly language?",
        "How does the computer system handle data representation for different types?"
    ],
    "introduction_to_computer_science":[
        "How do I create a basic Python program with user input?",
        "What's the difference between procedural and object-oriented programming?",
        "How do I implement a for loop in Python?",
        "Can you explain how dictionaries work in Python?",
        "What is the purpose of exception handling in programming?",
        "How do I read and write to files in Python?",
        "What are the fundamentals of boolean logic in programming?",
        "How do function arguments work in Python?",
        "What is the difference between local and global variables?",
        "How do I create a custom Python module?",
        "What techniques can I use for decomposing complex problems?",
        "How do I implement inheritance in Python classes?",
        "What is the purpose of recursion in programming?",
        "How do I create a simple GUI application using tkinter?",
        "What are the fundamentals of backtracking algorithms?",
        "How does memory allocation work in Python?",
        "What are the best practices for designing Python classes?",
        "How do I work with CSV files in Python?",
        "What is the difference between shallow and deep copying?",
        "How do I use list comprehensions in Python?",
        "What are iterators and how do they work in Python?",
        "How can I implement collision detection in game development?",
        "What is polymorphism in object-oriented programming?",
        "How do I use Git for version control in programming projects?",
        "What's the process for creating a final project in Python?"
    ],
    "software_engineering":[
        "What are the key differences between agile and waterfall process models?",
        "How do you effectively document non-functional requirements?",
        "What techniques are used for requirements elicitation?",
        "How do you create a comprehensive use case diagram?",
        "What are GRASP patterns and how are they applied in software design?",
        "How do class diagrams represent relationships between objects?",
        "What is the purpose of interaction diagrams in software design?",
        "How do you measure software quality during development?",
        "What are the best practices for risk management in software projects?",
        "What is the difference between black box and white box testing?",
        "How do you create effective system sequence diagrams?",
        "What factors should be considered when estimating software project costs?",
        "How does software maintenance differ from software development?",
        "What are the principles of event-driven design in software engineering?",
        "How do domain models help in software development?",
        "What techniques are used for software project planning and scheduling?",
        "How can UML diagrams improve software design communication?",
        "What are the challenges in transitioning from design to code?",
        "How do you implement effective testing strategies for software systems?",
        "What methods are used for software project estimation?",
        "What is the role of software architecture in large-scale systems?",
        "How do you manage requirements changes during development?",
        "What techniques can improve software maintainability?",
        "How do you document software requirements effectively?",
        "What are the best practices for software team collaboration?"
    ],
    "statistics_for_social_science":[
        "What is the difference between descriptive and inferential statistics?",
        "How do you calculate the standard deviation of a dataset?",
        "What is the purpose of linear regression in statistical analysis?",
        "How do I interpret correlation coefficients in data analysis?",
        "What are the key components of experimental design in statistics?",
        "How do probability rules apply to compound events?",
        "What is the difference between dependent and independent events?",
        "How do you determine sample size for statistical significance?",
        "What is the central limit theorem and why is it important?",
        "How do confidence intervals help interpret statistical results?",
        "What is the difference between Type I and Type II errors in hypothesis testing?",
        "How do you analyze bivariate distributions in STATA?",
        "What is Simpson's paradox and how does it affect data interpretation?",
        "How do you calculate and interpret p-values in hypothesis testing?",
        "What are the properties of normal distributions in statistics?",
        "How do you conduct significance testing in regression analysis?",
        "What is the binomial distribution and when is it used?",
        "How do random variables differ from regular variables?",
        "What methods are used for testing statistical hypotheses?",
        "How do you analyze two-way tables in statistical analysis?",
        "What is the purpose of t-distributions in statistical testing?",
        "How do you interpret the results of a statistical experiment?",
        "What is the difference between populations and samples in statistics?",
        "How do transformations affect statistical distributions?",
        "What is Bayes' rule and how is it applied in statistical analysis?"
    ],
    "mental_health":[
        "What are effective strategies for managing anxiety symptoms?",
        "How can I recognize signs of depression in a friend or family member?",
        "What is the relationship between exercise and mental health?",
        "How does cognitive behavioral therapy work for treating depression?",
        "What are healthy coping mechanisms for stress management?",
        "How can mindfulness practices improve mental wellbeing?",
        "What is the difference between sadness and clinical depression?",
        "How can I support someone experiencing a panic attack?",
        "What are the warning signs of burnout and how can it be prevented?",
        "How does sleep quality affect mental health?",
        "What techniques help with managing intrusive thoughts?",
        "How can I build emotional resilience during difficult times?",
        "What are effective ways to set healthy boundaries in relationships?",
        "How does trauma affect the brain and mental health?",
        "What self-care practices are most effective for managing stress?",
        "How can I help a loved one who's struggling with mental health issues?",
        "What is the connection between nutrition and mental wellbeing?",
        "How do I know when it's time to seek professional mental health support?",
        "What strategies help with managing social anxiety in work environments?",
        "How can mindfulness meditation reduce symptoms of depression?",
        "What are productive ways to process grief and loss?",
        "How does cognitive restructuring help with negative thought patterns?",
        "What are effective techniques for managing work-related stress?",
        "How can I improve my self-esteem and reduce negative self-talk?",
        "What strategies help maintain mental health balance during major life transitions?"
    ],
    "physical_activity":[
        "What are the best exercises for beginners to start a fitness routine?",
        "How many minutes of cardio per week is recommended for heart health?",
        "What's the difference between HIIT and steady-state cardio training?",
        "How can I build a balanced strength training program?",
        "What exercises are most effective for core strength development?",
        "How do I properly warm up before intense physical activity?",
        "What's the optimal recovery time between strength training sessions?",
        "How can I increase my running endurance safely?",
        "What are the benefits of incorporating yoga into a fitness routine?",
        "How should I modify my workout routine as I age?",
        "What exercises can help improve posture and reduce back pain?",
        "How do I design a fitness plan that fits my busy schedule?",
        "What's the best approach to training for a 5K race?",
        "How can I prevent exercise-related injuries?",
        "What's the ideal balance between cardio and strength training?",
        "How does nutrition timing affect workout performance?",
        "What are effective exercises for improving flexibility?",
        "How can I stay motivated with my fitness routine long-term?",
        "What are the benefits of cross-training for overall fitness?",
        "How do I properly track progress in my fitness journey?",
        "What are the most effective bodyweight exercises for building strength?",
        "How does circuit training compare to traditional weight lifting?",
        "What fitness activities can be done with limited equipment at home?",
        "How can I incorporate active recovery days into my workout schedule?",
        "What are the best exercises for improving cardiovascular health?"
    ],
}

# Function to get all samples with their expected experts
def get_all_samples_with_experts():
    """
    Returns a list of tuples containing (query, expected_expert)
    """
    all_samples = []
    for expert, queries in samples.items():
        for query in queries:
            all_samples.append((query, expert))
    return all_samples